### PR TITLE
Lab4

### PR DESCRIPTION
**Pull request by Dzmitry-Bialotski**
https://dimasindro.github.io/BrowserChessApp/spa/    thats the final version of the project. You can login within "user1@mail.ru"
password: "123456" and "user2@mail.ru" password: "123456". Then you can create room and enter it with both accounts. Also I added functionality: "you can play with out using mouse". So press arrows on the keyboard to change current cell. Then press Enter and choose cell to move. Press Escape to go back to choosing cell to move from. Rating of users will change if there is checkmate or when one of users give up. Also I added functionality to change avatar and username in profile page.

### CODE REVIEW

**Comment by Dzmitry-Bialotski** [comment]
all the commits before "add spa" relate to lab3, they are here by chance

**Review by gmltA — COMMENTED** [review]
That's a <kbd>6</kbd>. And the resulting mark is also <kbd>6</kbd>. Tell me if you are ok with that.

**Comment by Dzmitry-Bialotski** [comment]
agree

**Review by gmltA — APPROVED** [review]
That's it then.
Good luck!

**Pull request merged**
